apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-app
  name: argocd-app-service
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
  selector:
    app: argocd-app
  type: NodePort
